name: algorithms_and_data_structures
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.6

dependencies:
  lints_y:
    git:
      url: https://github.com/Yogi-7y/Project-Y
      path: packages/lints
      ref: result
  meta: ^1.12.0

dev_dependencies:
  test: ^1.24.0
